/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a sign-in code
         * @description **Answers identically for a number we know and one we do not** — same status, same body. Anything else is a directory of which businesses work with us, queryable by anyone with a phone book, and for the operator whose number *is* known it confirms a target worth attacking.
         *
         *     The challenge is recorded either way, so the endpoint's timing cannot become the oracle its body carefully is not.
         *
         *     Rate-limited per IP. Every request costs an SMS once a sender exists, so the limit is a cost control as much as an abuse control.
         */
        post: operations["requestOperatorOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a code for a session
         * @description Wrong, expired, used and over-attempted codes all answer `401` with one message, for the same reason the request endpoint has one body.
         *
         *     The returned `operatorId` is for labelling the screen. It is **not accepted back** on any request in this document.
         */
        post: operations["createOperatorSession"];
        /**
         * Sign out
         * @description Revokes this session immediately. The token stops working on the next request.
         */
        delete: operations["deleteOperatorSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/step-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a code to the owner's phone
         * @description Elevates this session for ten minutes. The code goes to the **OWNER's** number whoever asks — a compromised MANAGER login must not be able to both request the elevation and receive the code that grants it.
         *
         *     Ten minutes is long enough to fill in bank details on a phone with a bad keyboard, and short enough that a session left open on a shared laptop at a dive shop is not still elevated after lunch.
         */
        post: operations["requestOperatorStepUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/step-up/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Use the code
         * @description The elevation is stamped on the session you already hold rather than returned as a second token — a client with two credentials keeps the elevated one as long as the ordinary one, which is the failure this avoids.
         *
         *     A code raised for one user cannot be spent on another's session, even within the same operator. The point of routing it to the owner is that the owner decides.
         */
        post: operations["verifyOperatorStepUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Changes to this account */
        get: operations["listOperatorChangeRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-requests/bank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change where the money goes
         * @description Three gates, not one: **OWNER only**, a code sent to the owner's phone (`step-up`), and then two 24-hour clocks before anything is live.
         *
         *     The objection window runs **before** approval so the real owner — who is messaged the moment it is raised — can stop it. The cooling window runs **after**, so even an approved change is still catchable. An objection window closing with nobody objecting does *not* approve anything; it moves the request into a human review queue. Auto-approving on silence would make the whole design a delay rather than a control.
         *
         *     Only the **last four digits** of the account number are stored. Nothing in this service pays anybody — the payout run does not read from here — so holding the full number would be a liability with no matching capability. It arrives out of band when a person sets the account up, confirming the last four against what the operator sees on their screen.
         *
         *     One at a time: two open bank changes would mean the second approval silently decides which account wins.
         */
        post: operations["requestBankChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/change-requests/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop a change you did not make
         * @description Works during the objection window **and** during cooling. A cooling change nobody can stop is just a slower mistake.
         *
         *     Deliberately **not** behind step-up. The person most likely to need this is the owner who just received a warning about a change they did not make, and making them pass another code first puts the emergency brake further away than the accelerator.
         */
        post: operations["cancelChangeRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who can get in
         * @description Active people and unaccepted invitations, in one list.
         */
        get: operations["listOperatorTeam"];
        put?: never;
        /**
         * Invite somebody
         * @description OWNER only. `MANAGER` or `STAFF` — **OWNER cannot be invited**, because the owner is the person whose bank account this is, and that is not a thing one login should be able to hand to a phone number.
         *
         *     A number already belonging to any operator is refused with the same message as any other failure, so this endpoint cannot be used to find out which businesses are on Yuvoy — the same reason sign-in answers identically for known and unknown numbers.
         *
         *     Re-inviting the same number replaces the open invitation rather than adding one, so a revoked invite is not undone by an older code still lying around.
         */
        post: operations["inviteOperatorUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invitation
         * @description Unauthenticated, because accepting an invitation is what somebody does before they have an account. Scoped by the invite code: hashed, attempt-limited, seven-day expiry.
         *
         *     **No session is minted here.** They sign in through the ordinary flow afterwards, so one code path creates operator sessions rather than two — and the second one would be the one written in a hurry.
         */
        post: operations["acceptOperatorInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/team/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove somebody
         * @description Their sessions are revoked in the same transaction. Marking a user removed while leaving a 14-day session alive is the difference between "we removed them" and "we removed them a fortnight from now", and the reason somebody is removed in a hurry is usually that the fortnight matters.
         *
         *     You cannot remove yourself, and you cannot remove the last owner — an account with no owner cannot approve a bank change, receive a step-up code, or invite anybody.
         */
        delete: operations["removeOperatorUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who am I and what may I do */
        get: operations["getOperatorMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * My bookings
         * @description Note the absence of an operator parameter. The tenant comes from the session.
         */
        get: operations["listOperatorBookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One booking
         * @description Another operator's booking answers `404`, identically to one that does not exist.
         */
        get: operations["getOperatorBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/relay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tell this traveller something
         * @description Operators do not see traveller phone numbers. This is how you reach them instead.
         *
         *     An intent's `detail` travels inside an approved WhatsApp template and lands on the traveller's phone. A `note` does not: free text is stored against the booking and shown on their status page, and the message they receive is a pointer to it. That split is not a limitation to work around — unapproved text is undeliverable outside a service window, so a "note" that appeared to send as a message would mostly not arrive.
         *
         *     Sending is throttled per operator, not per user, and counts sends rather than recipients.
         */
        post: operations["relayToBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{id}/relay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tell everyone on this departure
         * @description The same act as the per-booking relay, addressed to every live booking on the departure. One send, one batch, one throttle count — telling thirty people the boat moved is one act of communication, and counting it per recipient would punish the operator with the fuller boat.
         *
         *     Reaches `converted` bookings and unexpired holds only. A lapsed hold is somebody who is not coming, and a declined request is somebody already told no.
         */
        post: operations["relayToSlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Requests waiting for an answer
         * @description Request-mode departures hold nothing until you accept. A request that expires unanswered is a traveller told no by a clock.
         *
         *     Ordered by how soon each expires rather than when it arrived, because the queue's job is to stop requests dying — so the one closest to death is first. `minutesToAnswer` is computed server-side so every client shows the same number.
         */
        get: operations["listOpenRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant the seats
         * @description This is the moment the seats come into existence. Before it the departure could sell nothing; after it, it can sell exactly this party.
         *
         *     Taken under the departure's row lock, so two staff answering two requests on two phones cannot together commit more seats than the boat holds. Requires OWNER or MANAGER.
         *
         *     On success the traveller has an ordinary hold with a clock on it — the same thing a direct-booking traveller gets at checkout — and is told to pay before it lapses.
         */
        post: operations["acceptRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Turn the request down
         * @description Cheap on purpose. A decline commits nothing and takes no lock, because the failure mode being designed against is an operator who lets requests rot rather than saying no.
         *
         *     `reasonCode` is a closed set. It is for us — an operator who declines everything is visible in aggregate — and the traveller reads a sentence derived from it, which always states that nothing was charged, because in every decline that is true and travellers do not know it.
         */
        post: operations["declineRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{id}/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who is coming
         * @description Confirmed bookings **and live holds**. A party mid-checkout at 08:40 may walk up at 08:55, and a manifest that omits them sends the operator into an argument they cannot win — their `state` is `holding` so the difference is visible. Lapsed holds, cancellations and declines are absent: they are on the record, and the record is not what the operator is holding.
         *
         *     No phone numbers (D-018). `reference` is what matches a walking-up human to a row; the traveller has it in every message we send them.
         *
         *     `?format=csv` returns the same data as a file, deterministically ordered so two exports can be diffed — which is exactly what somebody does when the head count and the app disagree. The CSV ends with a `TOTAL` row, because making somebody add a column of numbers on a dock is how the count goes wrong.
         */
        get: operations["getManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tick somebody off, or say how it ended
         * @description `arrived` is an observation at the meeting point and is **idempotent** — a second tap on a wet phone keeps the first arrival time and is not an error somebody has to read while eleven people wait.
         *
         *     `completed` and `no_show` are terminal outcomes that money hangs off, so both are refused before the departure time (`409 departure_has_not_started`). A trip that completed before it left is a number no payout run can be trusted to have derived honestly.
         *
         *     Re-settling an already-settled booking is refused rather than silently overwritten: an operator who marks a no-show as completed by mistake needs to see that.
         */
        post: operations["markAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{id}/offline-sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Seats you sold at the counter
         * @description A **report**, not a request, and it is accepted even when it is bad news. Refusing it would not un-sell the seats — it would only keep our numbers wrong until eleven people and a six-person boat meet at a jetty.
         *
         *     If the report creates an oversell the response says so plainly, names the bookings that lost their seats, and opens an honour incident against the operator. This is the one endpoint in the portal that deliberately refuses to be reassuring: an operator who taps "I sold 3 at the counter" and sees a cheerful tick has not understood what they did to three people who paid us.
         */
        post: operations["recordOfflineSale"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{id}/call-off": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * This departure cannot run
         * @description Cancels the departure, cancels every booking on it, refunds all of them **in full**, releases the holds and tells everybody — in one transaction. Cancelling without the refunds would leave people who paid staring at a cancelled trip and their money gone.
         *
         *     Full refunds regardless of the cancellation policy. Those tiers price a traveller changing their mind; nobody changed their mind here, and applying a 50% tier to somebody whose trip was called off by weather is the fastest way to lose a market where every traveller talks to the next one at the same guesthouse.
         *
         *     `confirmSlotId` must equal the departure's own id. Not a boolean: a checkbox is one mis-tap on a wet phone away from cancelling a full boat, and this is the only action in the portal that cannot be undone. Requires OWNER or MANAGER.
         */
        post: operations["callOffDeparture"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My departures */
        get: operations["listOperatorSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change how many seats a departure offers
         * @description **You cannot reduce a departure below what is already sold.** Not "should not" — the database refuses it, because the alternative is a traveller with a paid booking and no seat, discovered at a jetty at six in the morning.
         *
         *     Reducing to *exactly* what is sold is allowed: that closes the departure without stranding anyone. A refused reduction returns `409` with copy telling the operator what to do instead, which clients should render verbatim rather than replacing with a generic error.
         *
         *     Requires OWNER or MANAGER.
         */
        patch: operations["setSlotCapacity"];
        trace?: never;
    };
    "/blackouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close dates to new bookings
         * @description **Closing dates is not cancelling people.** This stops new sales and reports what the operator still owes travellers — including people mid-checkout, whose holds predate the closure and can still complete.
         *
         *     An operator who assumes closing the calendar cancelled the bookings will simply not turn up, so clients must render `note` when `existingBookings > 0`.
         *
         *     Requires OWNER or MANAGER.
         */
        post: operations["addBlackout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/earnings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What I have earned
         * @description Summed from figures **frozen at capture**, so a commission change today cannot restate what was earned last week. `state` is `provisional` until a payout period is locked — say so in the UI, because nobody should plan against a number that can still move.
         *
         *     Requires OWNER or MANAGER.
         */
        get: operations["getOperatorEarnings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/experiences/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose a change to a listing
         * @description **Never a write to the live listing.** A published listing is what travellers are booking against right now, and editing it in place lets a price change between somebody reading it and somebody paying.
         *
         *     Bookings already made are unaffected either way — their terms were snapshotted at checkout. Clients should say so, because the obvious assumption is the opposite.
         *
         *     Changes to price, safety notes, inclusions, requirements, duration or party size are *material* and need review before going live.
         */
        post: operations["submitExperienceRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/upload-intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get an upload slot for a reel
         * @description **Bytes never pass through this API.** The browser uploads directly to the video provider over tus, resumable in 5 MB chunks — on a 0.5-3 Mbps island uplink a non-resumable uploader is not slow, it is unusable.
         *
         *     `uploadUrl` is returned **once and never stored server-side**: it is a credential for writing video into our account. Treat it as a secret, use it immediately, and do not persist it client-side either.
         */
        post: operations["createUploadIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/upload-intents/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tell us the upload finished
         * @description A hint that it is worth polling, nothing more — **the client's claim is never trusted.** What decides is whether the provider has an asset that is in our account, ready, with a playback id, a poster and a duration.
         *
         *     `202` with `ready: false` is normal and not an error: the video is still processing. A job keeps polling whether or not the client comes back.
         */
        post: operations["confirmUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}/rights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attest to rights over this footage
         * @description **Attesting does not publish.** A reviewer checks it afterwards, and only their approval produces the verified rights record the database requires before a clip can appear anywhere. Say so in the UI — operators reasonably assume attesting is the last step.
         *
         *     `peopleConsentConfirmed` must be an explicit `true` or `false`, never defaulted and never omitted: consent of the people filmed is the one thing a moderator cannot check by watching.
         *
         *     `statementSha256` is the hash of the statement **as it was rendered to the operator**. Sending only a version number would mean that editing the wording without bumping the version silently turns every prior attestation into a claim about words nobody saw.
         */
        post: operations["attestMediaRights"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take a clip down
         * @description Two acts that fail independently, and only the first is transactional: it comes off Yuvoy immediately, and the original is deleted at the video provider shortly afterwards by a job. Conflating them would mean a provider outage keeps a clip live that the operator asked us to take down — and the reason they ask is sometimes that somebody in the footage objected, which is not a thing to be waiting on a third party for.
         *
         *     Asking twice succeeds: somebody requesting a clip come down that is already down should be told it is down, not told they did something wrong.
         *
         *     The reason is a closed set because the counts matter — `people_in_it_objected` arriving repeatedly for one operator is a consent problem in how they film, not a series of unrelated takedowns.
         */
        post: operations["withdrawMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/media/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Put an approved clip on a listing
         * @description Both the clip and the listing must belong to this operator; otherwise `404`. A clip that has not been approved also answers `404` — it is not yet a thing that can be published.
         */
        post: operations["publishMedia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                code: "invalid_input" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "rate_limited" | "internal_error" | "session_expired" | "account_not_active" | "operator_unavailable" | "would_strand_travellers" | "upload_in_progress" | "media_unavailable" | "invalid_reason_code" | "confirmation_required" | "invalid_role" | "step_up_required" | "request_not_open" | "departure_has_not_started" | "already_called_off" | "change_already_in_progress" | "change_already_decided" | "cannot_invite" | "cannot_remove";
                /** @description Human-readable; safe to show. */
                message: string;
                /** @description Field-level messages, keyed by field name. */
                details?: {
                    [key: string]: unknown;
                };
                requestId?: string;
            };
        };
        RelayRequest: {
            /** @enum {string} */
            intent: "time_change" | "meeting_point_change" | "weather_watch" | "bring_item" | "note";
            /**
             * @description The one fact this intent carries, and the only operator-supplied value that reaches a phone. Required for every intent except `note`, which carries none.
             *
             *     `time_change` and `weather_watch` take a 24-hour time (`09:30`). `meeting_point_change` takes a place (3–120 characters); `bring_item` takes a thing to bring (2–80). Both are restricted to letters, numbers and basic punctuation — not for injection safety (values are parameterised throughout) but because a template variable holding a URL or a newline renders as something nobody approved, and the provider is entitled to reject the whole message for it.
             */
            detail?: string;
            /** @description Free text. Shown on the traveller's status page and **never sent to a phone**. Required when `intent` is `note`, optional alongside any other intent. The cap is a product decision: a relay note is a sentence about a departure, not an essay somebody reads on island 3G. */
            note?: string;
        };
        RelayResult: {
            /** @description Groups one send across everyone it reached. */
            batchId?: string;
            intent?: string;
            /** @description How many people were actually told. */
            recipients?: number;
        };
        OpenRequest: {
            id?: string;
            slotId?: string;
            experience?: string;
            guests?: number;
            /** Format: date-time */
            startsAt?: string;
            timezone?: string;
            /** Format: date-time */
            requestedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            contactName?: string;
            /** @description Seats still grantable on this departure before its physical capacity is reached. Shown beside the request because "accept" with no sense of what is left is a decision made blind. */
            seatsGrantable?: number;
            /** @description Never negative. Computed server-side so every client agrees. */
            minutesToAnswer?: number;
        };
        RequestAnswer: {
            id?: string;
            /** @description `active` after an accept, `released` after a decline. */
            state?: string;
            /**
             * Format: date-time
             * @description Set on acceptance: the traveller now holds seats with a clock on them, and must pay before it lapses. Null on a decline.
             */
            holdExpiresAt?: string | null;
        };
        Manifest: {
            slotId?: string;
            experience?: string;
            /** Format: date-time */
            startsAt?: string;
            timezone?: string;
            meetingPoint?: string;
            /** @enum {string} */
            status?: "open" | "closed" | "cancelled";
            /** @description Present only when the departure is off. */
            calledOff?: {
                reasonCode?: string;
            };
            parties?: {
                /** @description Empty for a party still holding. */
                bookingId?: string;
                reference?: string;
                name?: string;
                guests?: number;
                /** @description `holding` for a live hold; otherwise the booking's fulfilment state. */
                state?: string;
                arrived?: boolean;
                /** Format: date-time */
                arrivedAt?: string;
            }[];
            /** @description Computed server-side so three clients cannot disagree about them on a dock. `seatsSold` and `seatsSoldOffline` answer different questions and are deliberately separate. */
            totals?: {
                parties?: number;
                guests?: number;
                arrived?: number;
                seatsSold?: number;
                seatsSoldOffline?: number;
            };
        };
        OfflineSaleResult: {
            seatsRecorded?: number;
            /** @description Never negative. An oversell is an incident, not a number on a screen. */
            seatsRemaining?: number;
            totalSoldOffline?: number;
            /** @description **Present means travellers who paid us now have no seat.** Do not render a success state when this is set. */
            oversold?: {
                guests?: number;
                bookings?: string[];
                message?: string;
                incidentId?: string;
            };
        };
        CallOffResult: {
            slotId?: string;
            reasonCode?: string;
            bookingsCancelled?: number;
            guestsAffected?: number;
            /** Format: int64 */
            refundedPaise?: number;
            holdsReleased?: number;
        };
        ChangeRequest: {
            id?: string;
            kind?: string;
            /**
             * @description `objection_window` → the owner can still stop it and no human has looked. `pending` → the window closed without objection and it is awaiting review. `cooling` → approved but not yet live, and still stoppable. `applied` → live.
             * @enum {string}
             */
            state?: "pending" | "objection_window" | "cooling" | "approved" | "rejected" | "withdrawn" | "applied";
            /** @description Masked. Never a full account number. */
            summary?: string;
            /** Format: date-time */
            requestedAt?: string;
            /** Format: date-time */
            objectionUntil?: string | null;
            /** Format: date-time */
            coolingUntil?: string | null;
        };
        TeamMember: {
            id?: string;
            name?: string;
            roles?: ("OWNER" | "MANAGER" | "STAFF")[];
            state?: string;
            /** @description An invitation nobody has accepted yet. `id` is the invitation, not a user. */
            pending?: boolean;
            /** Format: date-time */
            lastSeenAt?: string;
            /**
             * @description The last four digits of the number this person signs in with, or that an unaccepted invitation was sent to.
             *
             *     **Why the list carries a number at all.** An invitation is the only way into an operator account that starts with a human typing a number, so it is the only place a typo grants access — at STAFF, every departure's manifest; at MANAGER, capacity, closed dates, earnings and call-off. Without something to check against, an owner sees "Ramesh Toppo · Invited" and cannot tell that the last two digits were transposed at six in the morning.
             *
             *     **Why only four.** Enough to catch a transposition, not enough to be a directory of an operator's staff. The full number is masked in SQL and never enters the API process, so it cannot reach a log line or an error string by accident.
             * @example ••••0132
             */
            phoneMasked?: string;
        };
        OperatorBooking: {
            id?: string;
            reference?: string;
            state?: string;
            guests?: number;
            experience?: string;
            slot?: {
                /** Format: date-time */
                startsAt?: string;
                timezone?: string;
            };
            /**
             * @description The name, and only the name. `whatsapp` was here and was **removed in M13** per D-018: a traveller gives us a number so we can tell them about their booking, not so it can be added to an operator's contacts.
             *
             *     To reach this traveller, use `POST /bookings/{id}/relay`. To identify them at the jetty, use `reference` — they have it in every message we send and on their status page, and it is already read aloud on a dock.
             */
            contact?: {
                name?: string;
            };
            /** Format: date-time */
            createdAt?: string;
            /**
             * @description What this one booking contributed, so an operator asking "why is this two hundred rupees less than I expected" can answer it here rather than by messaging us.
             *
             *     **These are the same frozen figures `/earnings` sums**, not a recomputation. Commission was frozen on this booking at capture, so a rate change today cannot restate what was earned last week, and this object cannot disagree with the total for arithmetic reasons.
             *
             *     **It can disagree for a window reason, and that is deliberate.** `/earnings` selects on `created_at` — when the money moved — while this list selects on the slot's `startsAt`, which is when the trip runs. A booking made in March for a trip in April belongs to March's earnings and April's manifest. So summing a screenful of these will NOT reproduce an earnings total unless the two windows were asked the same question. Reconcile one booking against itself, not a page against a period.
             *
             *     Absent on a booking that never captured — a `pending_request` awaiting its operator has moved no money and has none of this.
             */
            money?: {
                /**
                 * Format: int64
                 * @description What the traveller was actually charged, at capture.
                 */
                grossPaise: number;
                /**
                 * Format: int64
                 * @description Yuvoy's cut, frozen at capture against the rate in force then.
                 */
                commissionPaise: number;
                /**
                 * Format: int64
                 * @description Refunds against this booking that are requested, pending or processed. Live rather than frozen: a refund raised today changes what is owed, and hiding that until settlement would make the screen wrong in the operator's favour.
                 */
                refundsPaise: number;
                /**
                 * Format: int64
                 * @description `grossPaise - commissionPaise - refundsPaise`. Sent rather than left to the client so that every surface subtracts in the same order and no screen can invent a different answer.
                 */
                netPaise: number;
            };
        };
    };
    responses: {
        /** @description Something in the request needs fixing. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No session, or one that is no longer valid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Signed in, but this role may not do it. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The operator account itself cannot trade right now (suspended or offboarded). Distinct from a role refusal: the person is fine, the business relationship is not. */
        AccountNotActive: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such row — **or one belonging to another operator.** Deliberately indistinguishable. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests from this address. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    requestOperatorOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description E.164, e.g. `+919000000101` */
                    phone: string;
                };
            };
        };
        responses: {
            /** @description Always this. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sent: boolean;
                        /** @description Seconds the code stays usable. */
                        expiresIn: number;
                        /** @description **Development only.** Present when the service runs outside production so the login flow can be exercised without an SMS account. Never present in production; a client must never depend on it. */
                        devCode?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["RateLimited"];
        };
    };
    createOperatorSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    code: string;
                    /** @description A label the operator recognises. */
                    device?: string;
                };
            };
        };
        responses: {
            /** @description Signed in. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Opaque bearer. Present as `Authorization: Bearer <token>`. Sessions are long-lived on purpose (14 days idle, 90 absolute): an operator checks a manifest from a phone on a boat with intermittent signal, and forcing a login every few hours means the manifest is not consulted rather than consulted securely. */
                        token: string;
                        user: {
                            id?: string;
                            name?: string;
                            roles?: ("OWNER" | "MANAGER" | "STAFF")[];
                        };
                        operatorId: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AccountNotActive"];
            429: components["responses"]["RateLimited"];
        };
    };
    deleteOperatorSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestOperatorStepUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sent to the owner. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sent?: boolean;
                        expiresIn?: number;
                        /** @description Development only, exactly as on sign-in. Never in production. */
                        devCode?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    verifyOperatorStepUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description Elevated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date-time */
                        steppedUpUntil?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listOperatorChangeRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description This operator's account changes, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requests?: components["schemas"]["ChangeRequest"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestBankChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accountHolder: string;
                    /** @description 9-18 digits. */
                    accountNumber: string;
                    /** @description Like HDFC0001234. */
                    ifsc: string;
                    bankName?: string;
                };
            };
        };
        responses: {
            /** @description Raised, and the owner has been messaged. Not live. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        state?: string;
                        /** @description Masked — last four digits only. */
                        summary?: string;
                        /** Format: date-time */
                        objectionUntil?: string;
                        whatHappensNext?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description `step_up_required` — ask for a code first. Also returned to anyone who is not the OWNER. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `change_already_in_progress` — cancel the open one first. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cancelChangeRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stopped. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description OWNER only. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description `change_already_decided` — it has already gone through. Distinguished from 404 on purpose: "we cannot find it" and "it already happened" mean very different things to somebody who has just realised their account was compromised. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOperatorTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The team. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        team?: components["schemas"]["TeamMember"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    inviteOperatorUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    name: string;
                    /** @enum {string} */
                    role: "MANAGER" | "STAFF";
                };
            };
        };
        responses: {
            /** @description Sent. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sent?: boolean;
                        /** @description Development only. */
                        devCode?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description OWNER only. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `cannot_invite` — one message for every failure, deliberately. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    acceptOperatorInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    phone: string;
                    code: string;
                };
            };
        };
        responses: {
            /** @description Accepted. Sign in next. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accepted?: boolean;
                        next?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    removeOperatorUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description OWNER only. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description `cannot_remove` — yourself, or the last owner. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getOperatorMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id?: string;
                        name?: string;
                        roles?: string[];
                        operatorId?: string;
                        /** @description OWNER or MANAGER. Capacity, closed dates, earnings and listing edits require it — a staff member who can see today's manifest does not need the margin on it. */
                        canManage?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AccountNotActive"];
        };
    };
    listOperatorBookings: {
        parameters: {
            query?: {
                state?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bookings for this operator only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: components["schemas"]["OperatorBooking"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getOperatorBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The booking. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperatorBooking"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    relayToBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelayRequest"];
            };
        };
        responses: {
            /** @description Queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelayResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description `nobody_to_tell` — this booking is no longer live, so there was nobody to send to. Deliberately not a success: "sent to 0 people" and "sent" must not look the same. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `too_many_updates` — too many relays from this operator this hour. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    relayToSlot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RelayRequest"];
            };
        };
        responses: {
            /** @description Queued. `recipients` is how many people were reached. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelayResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description `nobody_to_tell` — nobody has a live booking on this departure. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description `too_many_updates` — too many relays from this operator this hour. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOpenRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Open requests for this operator only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        requests?: components["schemas"]["OpenRequest"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    acceptRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Granted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestAnswer"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description STAFF cannot commit seats. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description `request_not_open` — already answered, or out of time. `grant_ceiling_exceeded` — that would put more people on the departure than it physically holds. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    declineRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reasonCode: "no_capacity" | "weather" | "not_operating" | "party_too_large" | "unsafe_for_party" | "other";
                };
            };
        };
        responses: {
            /** @description Declined. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestAnswer"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description STAFF cannot answer requests. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description `request_not_open` — already answered, or out of time. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getManifest: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The departure and everybody on it. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                    "text/csv": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    markAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    outcome: "arrived" | "completed" | "no_show";
                };
            };
        };
        responses: {
            /** @description Recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        outcome?: string;
                        /** Format: date-time */
                        arrivedAt?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description `departure_has_not_started` — wait until the trip sets off. `not_on_this_departure` — already settled, cancelled or declined. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    recordOfflineSale: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    seats: number;
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Recorded. Check `oversold` before showing a success state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfflineSaleResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    callOffDeparture: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reasonCode: "weather" | "equipment" | "staffing" | "safety" | "insufficient_numbers";
                    /** @description Shown on the travellers' status pages. Never rendered into a message — same rule as the relay. */
                    note?: string;
                    confirmSlotId: string;
                };
            };
        };
        responses: {
            /** @description Called off. The numbers are what it cost. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CallOffResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description STAFF cannot call off a departure. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            /** @description `already_called_off` — everybody on it has already been told. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listOperatorSlots: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Departures with live sold/remaining counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items?: {
                            id?: string;
                            experienceId?: string;
                            title?: string;
                            /** Format: date-time */
                            startsAt?: string;
                            timezone?: string;
                            seats?: number;
                            sold?: number;
                            remaining?: number;
                            status?: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    setSlotCapacity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    seats: number;
                };
            };
        };
        responses: {
            /** @description Capacity changed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description Would strand travellers who have already paid. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addBlackout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Omit to close all of this operator's departures. */
                    experienceId?: string;
                    /** Format: date */
                    from: string;
                    /** Format: date */
                    to: string;
                    /** @enum {string} */
                    reasonCode: "WEATHER" | "MAINTENANCE" | "STAFF" | "PERSONAL" | "SEASONAL" | "OTHER";
                    note?: string;
                };
            };
        };
        responses: {
            /** @description Dates closed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        closed?: boolean;
                        /** @description Bookings and live holds the operator still owes. */
                        existingBookings?: number;
                        note?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getOperatorEarnings: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Earnings for the window. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: date */
                        from?: string;
                        /** Format: date */
                        to?: string;
                        bookings?: number;
                        grossPaise?: number;
                        commissionPaise?: number;
                        refundsPaise?: number;
                        netPaise?: number;
                        /** @enum {string} */
                        state?: "provisional" | "open" | "locked" | "approved" | "exported" | "settled" | "void";
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    submitExperienceRevision: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Proposed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revisionId?: string;
                        state?: string;
                        needsReview?: boolean;
                        note?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createUploadIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An upload slot. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        intentId?: string;
                        /** Format: uri */
                        uploadUrl?: string;
                        /** Format: date-time */
                        expiresAt?: string;
                        maxBytes?: number;
                        maxSeconds?: number;
                        /** @enum {string} */
                        protocol?: "tus";
                        chunkBytes?: number;
                        aspectRatio?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description An upload is already in progress for this operator. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The asset exists and is ready. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ready?: boolean;
                        mediaAssetId?: string;
                    };
                };
            };
            /** @description Still processing. Poll again. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ready?: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    attestMediaRights: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    statementVersion: number;
                    statementSha256: string;
                    /** @enum {string} */
                    rightsType: "owned" | "licensed" | "operator_granted";
                    thirdPartyRef?: string;
                    licenceRef?: string;
                    peopleConsentConfirmed: boolean;
                    /** Format: date */
                    filmedOn?: string;
                    filmedAtLocation?: string;
                };
            };
        };
        responses: {
            /** @description Recorded and queued for review. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        attestationId?: string;
                        state?: string;
                        note?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    withdrawMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    reason: "operator_request" | "people_in_it_objected" | "no_longer_accurate" | "rights_lapsed";
                };
            };
        };
        responses: {
            /** @description Down. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        withdrawn?: boolean;
                        note?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    publishMedia: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    experienceId: string;
                    /**
                     * @default gallery
                     * @enum {string}
                     */
                    role?: "hero" | "gallery";
                };
            };
        };
        responses: {
            /** @description Published. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description This listing already shows as many clips as we display. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
