import Image from "next/image";
import { cn } from "@/lib/cn";

/**
 * The Yuvoy wordmark — the owner-delivered HORIZONTAL header lockup, the same
 * two files the marketing header and the traveller app carry.
 *
 * The ensō with its terracotta dot, the tracked YUVOY caps, the handwritten
 * "Experience more." and its tapered underline, side by side in one line. It
 * replaces the stacked near-square lockup this portal used to draw, which left
 * the three products wearing two different marks.
 *
 * Two files rather than one recoloured at runtime: a cream ensō is invisible
 * on cream and a forest one is invisible on forest. Generated by yuvoy-web's
 * scripts/generate-header-lockup.mjs and never hand-edited.
 *
 * Size it from outside with a height class, and the height means the DRAWING's
 * height: the generated variants crop the delivered canvas's empty margins.
 * The art's ~3.6:1 ratio sets the width from there.
 */

/* The cropped art box the generator emits (1247x347, ~3.6:1) — not the
   delivered 1600x500 canvas, a third of whose height is empty margin. */
const LOCKUP = { width: 1247, height: 347 } as const;

/** Keyed by the colour of the MARK, not of the surface behind it. */
const SRC = {
  cream: "/brand/yuvoy-lockup-on-dark.svg",
  forest: "/brand/yuvoy-lockup-on-light.svg",
} as const;

export function Wordmark({
  tone = "cream",
  className,
  priority = false,
}: {
  /** The colour of the MARK, chosen to contrast with the surface behind it. */
  tone?: "cream" | "forest";
  className?: string;
  priority?: boolean;
}) {
  return (
    <Image
      src={SRC[tone]}
      alt="Yuvoy"
      width={LOCKUP.width}
      height={LOCKUP.height}
      unoptimized
      priority={priority}
      className={cn("h-9 w-auto", className)}
    />
  );
}
